pipeline:
  identifier: Build_Python_full_CI_1736403055457
  name: Build Python-full-CI
  orgIdentifier: default
  projectIdentifier: Manish
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: manishrepo
        repoName: Python-full-CI
  stages:
    - stage:
        identifier: build
        name: Build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo
                  identifier: Echo
                  spec:
                    shell: Sh
                    command: echo Starting the CI Process.!!
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Python
                    buildTool: Pytest
                    runOnlySelectedTests: true
                    installCommands:
                      - python3 -m pip install pytest
                      - python3 -m pip install pytest-mock
                      - python3 -m pip install requests pytest pytest-cov
                    testCommand: |
                      python3 -m pytest --cov --cov-report term --cov-report xml:test/coverage.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - test/test/report.xml
                    coverage:
                      regex: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
                    artifacts:
                      reports:
                        junit: test/test/report.xml
                      paths:
                        - test/coverage.xml
                    enableTestSplitting: false
                    continueUponFailure: true
                    failOnError: false
              - step:
                  type: Run
                  name: Security Scan with Trivy
                  identifier: Security_Scan_Trivy
                  spec:
                    shell: Sh
                    command: |
                      echo "Starting security scan with Trivy..."
                      apt-get update && apt-get install -y wget
                      wget https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.deb
                      dpkg -i trivy_0.38.3_Linux-64bit.deb
                      trivy fs --vuln-type=os,library --security-checks vuln --format json --output trivy_report.json .
                      echo "Trivy security scan completed."
                    artifacts:
                      paths:
                        - trivy_report.json
                    continueUponFailure: true
                    failOnError: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
