pipeline:
  identifier: Build_Python_full_CI_1736403055457
  name: Build Python-full-CI
  orgIdentifier: default
  projectIdentifier: Manish
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: manishrepo
        repoName: Python-full-CI
  stages:
    - stage:
        identifier: build
        name: Build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo
                  identifier: Echo
                  spec:
                    shell: Sh
                    command: echo "Starting the CI Process.!!"
              - step:
                  type: Test
                  name: Run Tests
                  identifier: Install_Run_Tests
                  spec:
                    shell: Sh
                    command: |
                      echo "Installing dependencies and running tests..."
                      pip install pytest pytest-mock requests pytest-cov
                      pytest --cov --cov-report term --cov-report xml:coverage.xml
                  artifacts:
                    paths:
                      - coverage.xml
                    continueUponFailure: true
                    failOnError: false
              - step:
                  type: Run
                  name: Security Scan with Trivy
                  identifier: Security_Scan_Trivy
                  spec:
                    shell: Sh
                    command: |
                      echo "Starting security scan with Trivy..."
                      apt-get update -y && apt-get install -y wget
                      wget https://github.com/aquasecurity/trivy/releases/download/v0.38.3/trivy_0.38.3_Linux-64bit.deb
                      dpkg -i trivy_0.38.3_Linux-64bit.deb || echo "Trivy installation failed!"
                      trivy fs --vuln-type=os,library --security-checks vuln --format json --output trivy_report.json . || echo "Trivy scan failed!"
                      echo "Trivy security scan completed."
                    artifacts:
                      paths:
                        - trivy_report.json
                    continueUponFailure: true
                    failOnError: false
              - step:
                  type: Run
                  name: Security Scan with Snyk
                  identifier: Security_Scan_Snyk
                  spec:
                    shell: Sh
                    command: |
                      echo "Starting security scan with Snyk..."
                      curl -sL https://github.com/snyk/snyk/releases/download/v1.120.0/snyk-linux -o snyk-linux
                      chmod +x snyk-linux
                      ./snyk-linux auth $SNYK_API_TOKEN
                      ./snyk-linux test --all-projects --json > snyk_report.json || echo "Snyk scan failed!"
                      echo "Snyk security scan completed."
                    artifacts:
                      paths:
                        - snyk_report.json
                    continueUponFailure: true
                    failOnError: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
