pipeline:
  identifier: Build_Python_full_CI_1736403055457
  name: Build Python-full-CI
  orgIdentifier: default
  projectIdentifier: Manish
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: manishrepo
        repoName: Python-full-CI
  stages:
    - stage:
        name: Analyzee
        identifier: Analyzee
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: f24d5cd96f5eb536aabe2ba2737ce9c93f84aa01
                      domain: https://sonarcloud.io
                      ssl: false
                    tool:
                      project_key: manish-alm-demo_harness-ci
