pipeline:
  identifier: Build_Python_full_CI_1736403055457
  name: Build Python-full-CI with SonarQube
  orgIdentifier: default
  projectIdentifier: Manish
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: manishrepo
        repoName: Python-full-CI
  stages:
    - stage:
        identifier: build
        name: Build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: JFROGharness
                    target: https://trialn7qznw.jfrog.io/artifactory/harness-ci-jfrog-build-info/
                    sourcePath: "**/*.py"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          sharedPaths:
            - /var/run
        type: CI
        description: ""
